version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: winter_app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    networks:
      - winter_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: database
      DB_USERNAME: vanshev
      DB_PASSWORD: vanshev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: winter_db
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: vanshev
      MYSQL_PASSWORD: vanshev
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - winter_network

networks:
  winter_network:
    driver: bridge

volumes:
  db_data:
